# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Carpe's Garden
subtitle:
description: 学习总结 思考感悟 知识管理
author: Chentao Yang
email: comery@live.com
language: zh-Hans
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://comery.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: [README.md, '*.html', demo/**, test/*]
commonweal: 404.html

avatar: https://github.com/comery/comery.github.io/tree/master/uploads/avatar.png
#    url: https://github.com/comery/comery.github.io/uploads/avatar.png

# Writing
new_post_name: :title.md # File name of new posts
#new_post_name: :year-:month-:day.md
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: 4
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: bioinformatics
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

## 修改归档页面、某一分类页面、某一标签页面的显示篇数
## 参考：http://theme-next.iissnan.com/faqs.html#setting-page-size
archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false

category_generator:
  per_page: 10

tag_generator:
  per_page: 10

# Extensions
## Plugins: https://hexo.io/plugins/
# RSS，要先进入站点文件夹根目录安装插件
# npm install hexo-generator-feed --save 即可
# 无需更多配置
# 参数说明查看 README：https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
# 文章数，0 为全部
  limit: 0
  hub:
# 是否包含文章内容
  content: true

# emoji 支持，教程见本文 6.3 节
githubEmojis:
  enable: true
  idName: github-emoji
  unicode: false
  styles:
  localEmojis:

## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
#type: git
#repo: git@github.com:comery/comery.github.io.git
#branch: master
#deploy:
#  type: git
#  repo: git@207.148.101.35:blog.git
#  branch: master

deploy:
  type: git
  repo: git@github.com:comery/comery.github.io.git
  branch: master

